# PAXP Config
bind: 0.0.0.0:5000
timeout: 0.5

resources:
  dsp: http://dsp:6001/dsp/v2
  adm: http://adm:8008/v1/adm/

logging:
  formatters:
    default:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      datefmt: '%FT%T'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      level: DEBUG
      filename: paxp.log
      maxBytes: 1000000
      backupCount: 3
  loggers:
    requests:
      level: ERROR
    werkzeug:
      level: DEBUG
  root:
      handlers: [console, file]
      level: DEBUG

# Client Config
req_file: request.json

req_headers:
    Content-Type: application/json
    User-Agent: Opera/9.90.(Windows NT 6.2; sl-SI) Presto/2.9.179 Version/10.00

result: result.json

# DSP config
dsp:
    s:
    - id: "110"
      name: 品友
      burl: http://dsp:6001/res/v2/110
      res_file: response.json
      notice_file: notice.json
      is_res: true

    tsleep: 5

    info:
      host: 0.0.0.0
      port: 6001

    adms:

    - id: c111001
      type: 1
      did: '110'
      data:
        img: http://exchange/image111001
        text: app is very good


tkit_log:
  formatters:
    default:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      datefmt: '%FT%T'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
    file:
      class: logging.FileHandler
      formatter: default
      level: DEBUG
      filename: tkit.log
  loggers:
    requests:
      level: INFO
    werkzeug:
      level: DEBUG
    sh:
      level: ERROR
  root:
      handlers: [console, file]
      level: INFO
