# PAXP Config
bind: 0.0.0.0:5000
timeout: 0.5

resources:
  dsp: http://dsp:6001/dsp/v2
  adm: http://adm:8008/v1/adm/

logging:
  formatters:
    default:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      datefmt: '%FT%T'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
    file:
      class: logging.handlers.RotatingFileHandler
      formatter: default
      level: DEBUG
      filename: paxp.log
      maxBytes: 1000000
      backupCount: 3
  loggers:
    requests:
      level: ERROR
    werkzeug:
      level: DEBUG
  root:
      handlers: [console, file]
      level: DEBUG

# Client Config
req_file: request.json

req_headers:
    Content-Type: application/json
    User-Agent: Mozilla/5.0 (iPod; U; CPU iPhone OS 3_1 like Mac OS X; en-US) AppleWebKit/532.43.2 (KHTML, like Gecko) Version/4.0.5 Mobile/8B115 Safari/6532.43.2

result: result.json

# DSP config
dsp:
    s:
    - id: "110"
      name: 品友
      burl: http://dsp:6001/res/v2/110
      res_file: response_110.json
      notice_file: notice_110.json
      is_res: true

    tsleep: 5

    info:
      host: 0.0.0.0
      port: 6001

    adms:

    - id: c111001
      type: 1
      did: '110'
      data:
        img: http://ad-exchange-server/imga20101
        text: 下载聚美优品App立马送代金券


tkit_log:
  formatters:
    default:
      format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'
      datefmt: '%FT%T'
  handlers:
    console:
      class: logging.StreamHandler
      formatter: default
      level: DEBUG
    file:
      class: logging.FileHandler
      formatter: default
      level: DEBUG
      filename: tkit.log
  loggers:
    requests:
      level: INFO
    werkzeug:
      level: DEBUG
    sh:
      level: ERROR
  root:
      handlers: [console, file]
      level: INFO
